### ISSUE TITLE
Feature: Enter (newline) in stdin

### ISSUE THREAD

**Issue by 7heMech** [FredHappyface/Android.Brainf#17]
Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar feature requests in the project's issue tracker
  to avoid duplicates.
- [x] I have searched existing issues to see if this feature has been discussed
  before.

## Feature Details
Can you make the stdin input accept enter, I think it's newline on mobile but I'm not sure

### Is your feature request related to a problem? Please describe

I came [across this program](https://www.linusakesson.net/programming/brainfuck/life.bf), but I have issues running it since it needs enter character.

**Comment by FredHappyface** [comment]
Thanks for the suggestion! Definitely agree this needs adding. I'll aim to get it added this week and in the next release

**Comment by FredHappyface** [comment]
Apologies for the delay on this one! It's next on my todo after my current task so I'm hoping to get it done this weekend all being well

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FredHappyface/Android.Brainf/releases/tag/20240330

Should be on google play and fdroid soon :)
