### ISSUE TITLE
Bug: No way to add control characters or null to stdin

### ISSUE THREAD

**Issue by UnderSampled** [FredHappyface/Android.Brainf#22]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

## Issue Details

Many possible bytes cannot be entered as input, most importantly null.

### Description

Null termination is very important to BF, yet there is no way to have multiple null-terminated strings in stdin.

### Expected Behavior

Perhaps some way of escaping, such as `\0`.

**Comment by FredHappyface** [comment]
Hi thanks for this! Implemented much of the logic for this supporting the following notations 

`\xNN` where N is a hex digit. For example `\x00`

`@[symbol];` for symbols for `\x00` through `\x20` (inclusive). For example `@NUL;` - this is less supported but was added to provide some convenience

Note these have unit tests and some basic fuzzing to check against forseen edge cases (and hopefully crashes :) ). Tested on device and with debug arrays for input and output showing the byte values in addition to normal text outputs. `\` escapes itself

Aiming to release this over the next few days

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FredHappyface/Android.Brainf/releases/tag/20240826
