### ISSUE TITLE
Bug: Empty input is not an error

### ISSUE THREAD

**Issue by easyaspi314** [FredHappyface/Android.Brainf#4]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Android 12
- Version: 2022.01.10

### Describe the bug

Brainf should set the result of `,` to `0` if there is no input left.

For example, take the cat program
```bf
,[.,]
```
Input: `hello`

### Expected outcome

Output: `hello`

### Actual outcome

`ERROR: Insufficient input supplied. Must be > 5. (instruction={3:','})`

**Comment by FredHappyface** [comment]
Hi thanks for the issue and apologies for the delay in getting back to you. This one had completely slipped off my radar. I've addressed it and should get an update out in the next couple weeks.
