### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by SirCrownguard** [FredHappyface/Android.Brainf#5]
Hello. I would like to make a voluntary Turkish translation if it's possible for your app. Is there a language file that you can give me because I don't know about programming? Thanks.

**Comment by FredHappyface** [comment]
Thanks so much for your interest in this!

I'm currently experimenting with a web based translation tool for another one of my apps (EweSticker) which should make it miles easier to contribute

In the meantime, would you be happy if I shared the "strings.xml" file

This file contains all of the text used by brainf

**Comment by FredHappyface** [comment]
The file is located at https://github.com/FredHappyface/Android.Brainf/blob/main/app/src/main/res/values/strings.xml

I've also attached this below 

[strings.txt](https://github.com/FredHappyface/Android.Brainf/files/12500574/strings.txt)

**Comment by SirCrownguard** [comment]
Thank you for sharing strings file. It makes me happy.

I would also be happy to do voluntary translation for the project you are currently working on, if possible.

**Comment by SirCrownguard** [comment]
Here we are.
[strings.txt](https://github.com/FredHappyface/Android.Brainf/files/12501127/strings.txt)

**Comment by FredHappyface** [comment]
Thank you very much! And sure, happy to share the other file too

**Comment by SirCrownguard** [comment]
You're welcome! When your new project is finished, you can open an Issue for translation on the project's GitHub page and tag me or contact me at the following email address: departure_impromptu788@aleeas.com
